import type { PostgrestError } from '@supabase/supabase-js';

import { supabase } from '../supabase';
import type { Tables } from '../db';
import { normalizePhone } from '../phone';

type InviteRow = Tables<'invites'>;

export type Invite = {
  id: string;
  fullName: string | null;
  phone: string | null;
  email: string | null;
  status: InviteRow['status'];
  role: InviteRow['role'];
  token: string;
  expiresAt: string;
  /** The link to send. Only meaningful while the invite is still pending. */
  url: string;
};

/**
 * Where an invite link points.
 *
 * `https://`, not the `yieldd://` scheme, because WhatsApp does not reliably
 * turn a custom scheme into a tappable link — and an invite nobody can tap is
 * not an invite. The app claims this path via App Links / Universal Links; on a
 * device without the app installed it opens the site, which is the right
 * fallback.
 */
export const INVITE_BASE_URL = 'https://yieldd.co/invite';

export function inviteUrl(token: string): string {
  return `${INVITE_BASE_URL}?token=${encodeURIComponent(token)}`;
}

function toInvite(row: InviteRow): Invite {
  return {
    id: row.id,
    fullName: row.full_name,
    phone: row.phone,
    email: row.email,
    status: row.status,
    role: row.role,
    token: row.token,
    expiresAt: row.expires_at,
    url: inviteUrl(row.token),
  };
}

export function describeInviteError(error: PostgrestError): string {
  if (error.code === '42501') return 'Only an admin can invite people.';
  if (error.code === '23514') return 'Each invite needs either a phone number or an email address.';
  if (__DEV__) console.warn('[invites]', error);
  return "Those invites didn't send. Check your connection and try again.";
}

export type InviteDraft = { name: string; phone: string; email?: string };

/**
 * Creates one `invites` row per person, each with its own token.
 *
 * One row per person, not one shared link, is the whole point: the token is
 * what `handle_new_user()` reads to put the new account in the right
 * organisation with `role = 'rep'`, and what marks the invite accepted. A
 * shared link would let one person redeem it and lock everyone else out.
 *
 * The token itself is generated by the database (`gen_random_bytes(16)`), so
 * the client never invents the secret.
 */
export async function createInvites(input: {
  organizationId: string;
  invitedBy: string;
  eventId: string | null;
  reps: InviteDraft[];
}): Promise<Invite[]> {
  const rows = input.reps
    .filter((rep) => rep.name.trim() && (rep.phone.trim() || rep.email?.trim()))
    .map((rep) => ({
      organization_id: input.organizationId,
      invited_by: input.invitedBy,
      event_id: input.eventId,
      full_name: rep.name.trim(),
      phone: rep.phone.trim() ? normalizePhone(rep.phone) : null,
      email: rep.email?.trim().toLowerCase() || null,
      role: 'rep' as const,
    }));

  if (!rows.length) return [];

  const { data, error } = await supabase.from('invites').insert(rows).select();
  if (error) throw new Error(describeInviteError(error));
  return (data as InviteRow[]).map(toInvite);
}

/** Invites already sent for an event — so re-entering the step doesn't duplicate them. */
export async function fetchEventInvites(eventId: string): Promise<Invite[]> {
  const { data, error } = await supabase
    .from('invites')
    .select('*')
    .eq('event_id', eventId)
    .order('created_at', { ascending: true });

  if (error) throw error;
  return (data as InviteRow[]).map(toInvite);
}

export async function revokeInvite(id: string): Promise<void> {
  const { error } = await supabase.from('invites').update({ status: 'revoked' }).eq('id', id);
  if (error) throw new Error(describeInviteError(error));
}

/** The message that goes out over WhatsApp, with the person's own link in it. */
export function inviteMessage(invite: Invite, opts: { eventName?: string; from?: string }): string {
  const where = opts.eventName ? `for ${opts.eventName}` : 'for our upcoming event';
  const who = opts.from ? `${opts.from} has invited you` : "You're invited";
  return `${who} to capture leads on Yieldd ${where}.\n\nTap to join: ${invite.url}\n\nThe link works once and expires in 14 days.`;
}
