// Thin helpers over the generated database types.
//
// Nothing outside this file should import `types/database.ts` directly. That
// file is regenerated by `npm run db:types` and must stay disposable — screens
// import domain types from `types/*` and mappers from `lib/mappers/*` instead.
//
// Two translations exist between the database and the UI, and both live in
// exactly one place on purpose:
//   1. Case. The database speaks lowercase enums ('new', 'hot', 'text'); the
//      screens speak Title Case ('New', 'Hot', 'Text'). See lib/mappers.
//   2. Money. Every money column is `bigint` paise; every screen renders ₹.
//      That conversion is here and nowhere else.

import type { Database } from '../types/database';

type PublicSchema = Database['public'];

export type Tables<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Row'];

export type Inserts<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Insert'];

export type Updates<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T]['Update'];

export type Enums<T extends keyof PublicSchema['Enums']> =
  PublicSchema['Enums'][T];

// ---------------------------------------------------------------------------
// Money
//
// Stored as bigint paise so nothing ever depends on float arithmetic. supabase-js
// returns bigint as a JS number, which is safe here: ₹90,07,19,92,54,740 would
// be needed to exceed Number.MAX_SAFE_INTEGER.
// ---------------------------------------------------------------------------

export function rupeesToPaise(rupees: number): number {
  return Math.round(rupees * 100);
}

export function paiseToRupees(paise: number): number {
  return paise / 100;
}

/**
 * Indian digit grouping — 8,40,000 rather than 840,000.
 *
 * Implemented by hand rather than via Intl.NumberFormat('en-IN') because
 * Hermes ships a trimmed ICU on some builds and silently falls back to Western
 * grouping, which would be wrong in a way nobody notices until a customer says
 * the number "looks foreign".
 */
export function formatPaise(
  paise: number | null | undefined,
  opts: { withSymbol?: boolean; fallback?: string } = {}
): string {
  const { withSymbol = true, fallback = '—' } = opts;
  if (paise == null) return fallback;

  const negative = paise < 0;
  const whole = Math.round(Math.abs(paise) / 100).toString();

  let grouped: string;
  if (whole.length <= 3) {
    grouped = whole;
  } else {
    const last3 = whole.slice(-3);
    const rest = whole.slice(0, -3);
    grouped = rest.replace(/\B(?=(\d{2})+(?!\d))/g, ',') + ',' + last3;
  }

  return `${negative ? '-' : ''}${withSymbol ? '₹' : ''}${grouped}`;
}

/** Parses "8,40,000" or "840000" from a text input into paise. */
export function parseRupeeInput(input: string): number | null {
  const cleaned = input.replace(/[^0-9.]/g, '');
  if (!cleaned) return null;
  const value = Number(cleaned);
  return Number.isFinite(value) ? rupeesToPaise(value) : null;
}
